/**
 * Which runtime strings each tool page needs, so each page ships only those.
 *
 * All ~600 runtime strings together are 60 KB of JSON (16–19 KB compressed)
 * — more than half again the size of a Portuguese tool page. A page can only
 * ever show the strings its own component asks for, plus those of the modules
 * it uses, so that is what it gets.
 *
 * A component's scope is:
 *   - its own __t/__tf keys;
 *   - the tr() keys of every module it imports, followed transitively;
 *   - the modules it reaches through the window.co* globals that
 *     [...tool].astro publishes (window.coCompressPdf → pdf-compress.js …);
 *   - values it translates at display time (DISPLAY_KEYS_BY_SOURCE), for the
 *     modules it uses;
 *   - SHARED: modules every tool page runs (file limits, library recovery).
 *
 * Writes src/i18n/ui-runtime-scopes.ts. runtime-strings.test.mjs regenerates
 * it in memory and fails if the committed file is stale:
 *   node scripts/i18n/build-scopes.mjs
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname, basename, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { runtimeKeys, DISPLAY_KEYS_BY_SOURCE } from './runtime-keys.mjs';

const TOOLS = 'src/components/tools';
const SCRIPTS = 'src/scripts';

/** Modules every tool page loads from [...tool].astro. */
const SHARED_MODULES = ['file-limits.js', 'ensure-lib.js', 'lib-bootstrap.js'];

/** window.co* globals → the module behind them. */
const GLOBALS = {
  coCompressPdf: 'pdf-compress.js', coPdfPresets: 'image-compress.js',
  coCompressOoxml: 'ooxml-compress.js', coCompressXlsx: 'xlsx-compress.js',
  coFileTooLarge: 'file-limits.js', coAnyFileTooLarge: 'file-limits.js',
  coNothingToConvert: 'file-limits.js', coMessageForError: 'ensure-lib.js',
};

/** Display-time keys, by the module whose data they translate. */
const DISPLAY_BY_MODULE = {};
for (const [label, list] of Object.entries(DISPLAY_KEYS_BY_SOURCE)) {
  const m = label.match(/^src\/(?:scripts|components\/tools)\/([\w.-]+)/);
  if (m) (DISPLAY_BY_MODULE[m[1]] ||= []).push(...list);
}

function importsOf(file) {
  const src = readFileSync(file, 'utf8');
  const out = new Set();
  for (const m of src.matchAll(/from\s+['"]([^'"]+\.js)['"]/g)) {
    const target = resolve(dirname(file), m[1]);
    if (existsSync(target) && target.includes(resolve(SCRIPTS))) out.add(basename(target));
  }
  for (const [g, mod] of Object.entries(GLOBALS)) if (new RegExp('\\b' + g + '\\b').test(src)) out.add(mod);
  return out;
}

function modulesReached(file) {
  const seen = new Set();
  const stack = [...importsOf(file)];
  while (stack.length) {
    const m = stack.pop();
    if (seen.has(m)) continue;
    seen.add(m);
    for (const n of importsOf(join(SCRIPTS, m))) stack.push(n);
  }
  return seen;
}

export function buildScopes() {
  const { keys } = runtimeKeys();
  // file (normalised) → keys found in it
  const byFile = new Map();
  for (const [k, where] of keys) {
    for (const w of where) {
      const f = w.replace(/\\/g, '/').replace(/:\d+$/, '');
      if (!byFile.has(f)) byFile.set(f, new Set());
      byFile.get(f).add(k);
    }
  }
  const keysOfModule = (m) => new Set([
    ...(byFile.get(`${SCRIPTS}/${m}`) || []),
    ...(DISPLAY_BY_MODULE[m] || []),
  ]);

  const shared = new Set();
  for (const m of SHARED_MODULES) for (const k of keysOfModule(m)) shared.add(k);
  for (const m of SHARED_MODULES) for (const n of modulesReached(join(SCRIPTS, m))) for (const k of keysOfModule(n)) shared.add(k);

  const scopes = { shared: [...shared].sort() };
  for (const f of readdirSync(TOOLS).filter((f) => f.endsWith('.astro')).sort()) {
    const name = f.replace(/\.astro$/, '');
    const set = new Set([...(byFile.get(`${TOOLS}/${f}`) || []), ...(DISPLAY_BY_MODULE[f] || [])]);
    for (const m of modulesReached(join(TOOLS, f))) for (const k of keysOfModule(m)) set.add(k);
    for (const k of shared) set.delete(k);
    if (set.size) scopes[name] = [...set].sort();
  }
  return scopes;
}

export function renderScopes(scopes) {
  let out = `/**
 * Runtime strings each tool page ships, by tool component. GENERATED by
 * scripts/i18n/build-scopes.mjs — do not edit; rerun it. The runtime-strings
 * test fails when this file is stale.
 */
export const runtimeScopes: Record<string, string[]> = {\n`;
  for (const [k, list] of Object.entries(scopes)) {
    out += `  ${JSON.stringify(k)}: [\n` + list.map((s) => '    ' + JSON.stringify(s) + ',\n').join('') + '  ],\n';
  }
  return out + '};\n';
}

export const SCOPES_FILE = 'src/i18n/ui-runtime-scopes.ts';

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const scopes = buildScopes();
  writeFileSync(SCOPES_FILE, renderScopes(scopes));
  const sizes = Object.entries(scopes).map(([k, v]) => `${k} ${v.length}`).join(', ');
  console.log('wrote', SCOPES_FILE, '—', sizes);
}
