/**
 * Where test artifacts live. One answer, imported everywhere.
 *
 * These paths used to be built by hand in seventeen places across twenty
 * files — `join(HERE, 'fixtures', 'files')` in the harness, `join(process
 * .cwd(), 'scripts', 'fidelity', 'fixtures', 'files')` in the verifiers,
 * `new URL('test.pdf', import.meta.url)` in the pdf-to-docx tests — which
 * meant artifacts accumulated in three separate directories and moving any of
 * them meant finding every spelling first.
 *
 * The split that matters is **authored vs generated**, not which suite owns
 * it. The builders, recipes, runners and tests are source and stay in
 * `scripts/`. Everything they *produce* is disposable and lands here, so the
 * whole lot can be deleted and rebuilt without touching a line of code:
 *
 *   testing/fixtures/   inputs — the torture files, built by
 *                       `npm run fidelity:fixtures`
 *   testing/out/        outputs — converted files and report.json, written by
 *                       whichever suite just ran
 *
 * Both are gitignored for the same reason: they are reproducible from the
 * builders, and a repo that ships a megabyte of generated .xlsx is a repo
 * nobody can review.
 */
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { mkdirSync } from 'node:fs';

/* Resolved from this file rather than from process.cwd(), so a suite works
   when run from a subdirectory. Three of the verifiers assumed the repo root
   and silently looked in the wrong place from anywhere else. */
const HERE = dirname(fileURLToPath(import.meta.url));

/** Repo root — this file lives at <root>/scripts/. */
export const ROOT = join(HERE, '..');

/** Everything generated by the test suites. */
export const TESTING = join(ROOT, 'testing');

/** Generated inputs: torture.pdf, torture.xlsx, and the rest. */
export const FIXTURES = join(TESTING, 'fixtures');

/** Generated outputs: converted files, report.json, screenshots. */
export const OUT = join(TESTING, 'out');

/**
 * A browser profile directory the suites own, one per suite.
 *
 * Puppeteer otherwise creates a fresh profile under the system temp directory
 * and deletes it on close. On this machine that delete loses a race with
 * whatever else scans `%TEMP%` and throws `EBUSY: resource busy or locked`
 * from an async cleanup with no suite frame in the stack — which kills the
 * process wherever it happens to be. `npm run mobile` against production died
 * that way three times, at a different page each time, while the same build
 * passed locally.
 *
 * A directory we create ourselves is not cleaned up by puppeteer at all, so
 * the race has nothing to lose. One per suite, because a profile can only be
 * held by one browser at a time and two suites running at once would then
 * fail to launch rather than fail to clean up.
 */
export const browserProfile = (name) => {
  const dir = join(TESTING, 'browser-profiles', name);
  mkdirSync(dir, { recursive: true });
  return dir;
};

/** A fixture by name. */
export const fixture = (name) => join(FIXTURES, name);

/** An output path by name. */
export const output = (name) => join(OUT, name);

/**
 * Make sure both directories exist.
 *
 * Called by anything that writes. They are gitignored, so on a fresh clone
 * neither exists, and a missing directory is an ENOENT at the moment of
 * writing rather than a clear message at startup.
 */
export function ensureTestingDirs() {
  mkdirSync(FIXTURES, { recursive: true });
  mkdirSync(OUT, { recursive: true });
}
